name: Nightly Build
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - name: Create a tag for the archive
        run: echo "TAG=$(date +%F)" >> $GITHUB_OUTPUT
        id: tag
        
      - name: Starting the nightly build for ${{ steps.tag.outputs.TAG }}
        run: echo "The tag is $TAG"
        
      - name: Check out the code
        uses: actions/checkout@v4
        
      - name: Create the artifact
        run: tar -cvf nightly-$TAG.tar ./*
        
      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
         name: nightly-$TAG.tar
         path: nightly-$TAG.tar

